main:
  - name: Bio
    url: /
    weight: 10
  - name: News
    url: /#news
    weight: 11
  - name: Publications
    url: /#publications
    weight: 12
  - name: Experience
    url: experience/
    weight: 20
