# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: Anton Matsson's personal website
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: navbar
    fixed_to_top: true
    show_search: true
    show_theme_chooser: false
    logo:
      text: Anton Matsson

# Site footer
footer:
  copyright:
    notice: "© {year} Anton Matsson. This work is licensed under {license}."
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: Jan 2, 2006
  time_format: 3:04 PM

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false

# Sponsorship
i_am_a_sponsor: true
